version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
     - ./mysql/dump/:/docker-entrypoint-initdb.d
    environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_USER: ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     MYSQL_DATABASE: ${MYSQL_DATABASE}
     APP_NAME: ${APP_NAME}
    ports:
     - ${DB_PORT}:3306
  app:
    build: ./app
    depends_on:
     - db
    volumes:
     - ./src:/var/www/html/${APP_NAME}:cached
     - ./images/products:/var/www/html/${APP_NAME}/web/images/products
#     - ./app/config/parameters.yml:/var/www/html/${APP_NAME}/app/config/parameters.yml
#     - ./app/config/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  web-srv:
    image: nginx
    ports:
     - ${WEB_SRV_PORT}:80
    volumes:
     - ./nginx/configs/conf.d/:/etc/nginx/conf.d/
     - ./nginx/configs/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/configs/.htpasswd:/etc/nginx/.htpasswd
    volumes_from:
     - app